[package]
name = "apalis-cron"
version = "1.0.0-alpha.1"
edition = "2024"
repository = "https://github.com/apalis-dev/apalis-cron"
authors = ["Njuguna Mureithi <mureithinjuguna@gmail.com>"]
license = "MIT"
description = "A simple and extensible library for scheduling recurring tasks in rust."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["cron"]
## Enable support for `cron` crate
cron = ["dep:cron"]
docsrs = ["dep:document-features"]
## Enable serde support
serde = ["dep:serde", "chrono/serde", "apalis-core/serde"]
## Enable support for `english-to-cron` crate
english = ["dep:english-to-cron", "dep:cron"]

[dependencies]
apalis-core = { version = "1.0.0-alpha.1", default-features = false, features = [
    "sleep",
] }
cron = { version = "0.15.0", optional = true }
futures-util = { version = "0.3.30", default-features = false }
chrono = { version = "0.4.38", default-features = false, features = ["clock"] }
serde = { version = "1.0", features = ["derive"], optional = true }
ulid = { version = "1" }
english-to-cron = { version = "0.1.6", optional = true }

[dependencies.document-features]
version = "0.2"
optional = true

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tower = { version = "0.5", features = ["full"] }
apalis-core = { version = "1.0.0-alpha.1", default-features = false, features = [
    "json",
] }


[package.metadata.docs.rs]
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]
all-features = true
